default_config:
automation: !include_dir_merge_list automation
script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes
fan: !include templates/fan.yaml
google_assistant: !include templates/google_assistant.yaml
input_boolean: !include templates/input_boolean.yaml
input_number: !include templates/input_number.yaml
sensor: !include templates/sensor.yaml
input_datetime: !include templates/input_datetime.yaml



http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 172.18.0.0/16

frontend:
  themes: !include_dir_merge_named themes

  extra_module_url:
  - /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524421
logger:
  default: info
#  logs:
#    custom_components.xiaomi_miio_fan: debug
#    miio.miioprotocol: debug
lovelace:
  resource_mode: yaml
  resources: !include dashboards/resources.yaml
  dashboards:
    lovelace:
      mode: yaml
      title: Resumen
      icon: mdi:view-dashboard
      show_in_sidebar: true
      require_admin: false
      filename: dashboards/resumen/dashboard.yaml
    dashboard-wallpanel:
      mode: yaml
      title: wallpanel
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      require_admin: false
      filename: dashboards/wallpanel/dashboard.yaml
