services:
  wyoming-piper:
    image: rhasspy/wyoming-piper:latest
    container_name: wyoming-piper
    restart: unless-stopped
    ports:
      - "9011:10200"
    volumes:
      - /docker/piper:/data
    command: [
      "--voice", "es_ES-mls_10246-low",
      "--uri", "tcp://0.0.0.0:10200"
    ]
    networks:
      - homeassistant

  wyoming-whisper:
    image: rhasspy/wyoming-whisper:latest
    container_name: wyoming-whisper
    restart: unless-stopped
    ports:
      - "9012:10300"
    volumes:
      - /docker/whisper:/data
    command: [
      "--model", "small-int8",
      "--language", "es",
      "--uri", "tcp://0.0.0.0:10300"
    ]
    networks:
      - homeassistant

networks:
  homeassistant:
    external: true