version: "3.5"
services:
  vscode:
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: vscode
    volumes:
      - /docker/vscode/config:/config
      - /docker:/config/workspace
    ports:
      - 9003:8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: always
    networks:
      - homeassistant

  bluetooth:
    image: theengs/gateway
    container_name: bluetooth
    privileged: true
    restart: always
    healthcheck:
      disable: true
    environment:
      - MQTT_HOST=host.docker.internal
      - MQTT_USERNAME=hass
      - MQTT_PASSWORD=${MQTT_PASS}
      - HAAS_DISCOVERY=true
      - DISCOVERY=true
      - PUBLISH_ALL=false
      - DISCOVERY_TOPIC=miguel
      - DISCOVERY_DEVICE_NAME=test
    volumes:
      - /var/run/dbus:/var/run/dbus
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - /docker/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    ports:
      - "9011:6052"
    networks:
      - homeassistant
      
networks:
  homeassistant:
    external: true
