version: '3.5'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /docker/homeassistant:/config
      - /docker/homeassistant/docker/run:/etc/services.d/home-assistant/run
      - /etc/localtime:/etc/localtime:ro
      #- /run/dbus:/run/dbus:ro
    restart: always
    networks:
      - homeassistant
    environment:
        - TZ=America/New_York
        - PUID=1000
        - PGID=1000
        - UMASK=007
        - PACKAGES=iputils

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt 
    restart: always
    volumes:
      - /docker/zigbee/:/app/data/
    devices:
      - "/dev/ttyUSB0" #lsusb -> Silicon Labs CP210x UART Bridge
    networks:
        - homeassistant

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt 
    networks:
        - homeassistant
    ports:
        - "1883:1883"
    volumes:
      - /docker/mqtt:/mosquitto
      - /docker/mqtt/data:/mosquitto/data
      - /docker/mqtt/log:/mosquitto/log
    restart: always

networks:
  homeassistant:
      external: true
