services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /docker/homeassistant-bind:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - homeassistant
    environment:
      - TZ=America/New_York
    #ports:
    #    - 8443:8443

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: always
    volumes:
      - /docker/zigbee/:/app/data/
    devices:
      - "/dev/ttyUSB0" #lsusb -> Silicon Labs CP210x UART Bridge
    networks:
      - homeassistant
    ports:
      - 9010:8080

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    networks:
      - homeassistant
    ports:
      - "1883:1883"
    volumes:
      - /docker/mqtt:/mosquitto
      - /docker/mqtt/data:/mosquitto/data
      - /docker/mqtt/log:/mosquitto/log
    restart: always

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "9002:81" #for management purposes
    volumes:
      - /docker/nginx/data:/data
      - /docker/nginx/letsencrypt:/etc/letsencrypt
      - /docker/homeassistant/compose/index.html:/var/www/html/index.html
    networks:
      - homeassistant
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s

  cloudflare:
    image: cloudflare/cloudflared
    container_name: cloudflare
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    networks:
      - homeassistant
    restart: always

networks:
  homeassistant:
    external: true
