services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 9020:8096
    volumes:
      - /docker/jellyfin/config:/config
      - /home/miguel/Videos:/media
    restart: "unless-stopped"
    networks:
      - homeassistant

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    networks:
      - homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 9021:7878
    volumes:
      - /docker/radarr-config:/config
      - /home/miguel/Videos:/downloads
    restart: "unless-stopped"

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/sonarr-config:/config
      - /home/miguel/Videos:/downloads
    ports:
      - 9022:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    networks:
      - homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/prowlarr-config:/config
    ports:
      - 9023:9696
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    networks:
      - homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/bazarr-config:/config
      - /home/miguel/Videos/movies:/downloads/movies
      - /home/miguel/Videos/tvshows:/downloads/tvshows
    ports:
      - 9024:6767
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=9025
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /docker/qbittorrent/config:/config
      - /home/miguel/Videos:/downloads
    ports:
      - 9025:9025
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - homeassistant

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    networks:
      - homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - FB_NOAUTH=noauth
    volumes:
      - /home/miguel/Videos:/srv
      - /docker/filebrowser/filebrowser.db:/database/filebrowser.db
      - /docker/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 9026:80
    restart: unless-stopped

networks:
  homeassistant:
    external: true
