version: "3.5"
services:
  remica-scraper:
    build: ../remica_scraper
    container_name: remica-scraper
    restart: always
    networks:
      - homeassistant
    environment:
      - REMICA_USERNAME=${REMICA_USERNAME}
      - REMICA_PASSWORD=${REMICA_PASSWORD}
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - MQTT_TOPIC=remica/consumo
      - TZ=Europe/Madrid
    volumes:
      - /docker/remica:/tmp
    # Ejecutar cada día a las 8:00 AM
    # Para ejecutar periódicamente, usa cron o configura un comando con sleep
    command: >
      sh -c "while true; do
        python remica_scraper.py;
        echo 'Esperando 24 horas hasta la próxima ejecución...';
        sleep 86400;
      done"

networks:
  homeassistant:
    external: true
