version: "3.5"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homeassistant

  duplicati:
    image: duplicati/duplicati
    container_name: duplicati
    restart: unless-stopped
    command: /usr/bin/duplicati-server --webservice-port=8200 --webservice-interface=any --webservice-allowed-hostnames=*
    ports:
      - "8200:8200"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/duplicati/config:/config
      - /docker/duplicati/data:/data
      - /docker/homeassistant:/source/homeassistant:ro
      - /docker/mqtt:/source/mqtt:ro
      - /docker/nginx:/source/nginx:ro
      - /docker/zigbee:/source/zigbee:ro
    networks:
      - homeassistant

networks:
  homeassistant:
    external: true
