version: "3.5"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --schedule "0 0 4 * * *" --cleanup --remove-volumes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homeassistant

  duplicati:
    image: duplicati/duplicati
    container_name: duplicati
    restart: unless-stopped
    command: /usr/bin/duplicati-server --webservice-port=8200 --webservice-interface=any --webservice-allowed-hostnames=*
    ports:
      - "9004:8200"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/duplicati/config:/config
      - /docker/duplicati/data:/data
      - /docker:/source:ro
      - /media/backup:/target
    networks:
      - homeassistant

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - /docker/adguard/work:/opt/adguardhome/work
      - /docker/adguard/conf:/opt/adguardhome/conf
    network_mode: host

networks:
  homeassistant:
    external: true
