version: "3.5"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --schedule "0 0 4 * * *" --cleanup --remove-volumes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL}
    networks:
      - homeassistant

  duplicati:
    image: duplicati/duplicati
    container_name: duplicati
    restart: unless-stopped
    command: /opt/duplicati/duplicati-server --disable-db-encryption --webservice-allowed-hostnames=* --log-level=Verbose --log-console=true
    ports:
      - "9004:8200"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/duplicati/config:/config
      - /docker/duplicati/data:/data
      - /docker:/source:ro
    networks:
      - homeassistant

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - /docker/adguard/work:/opt/adguardhome/work
      - /docker/adguard/conf:/opt/adguardhome/conf
    network_mode: host

  mailserver:
    image: miguellobato84/smtp-gmail-relay:latest
    container_name: mailserver
    environment:
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    restart: always
    networks:
      - homeassistant

  speedtest-tracker:
      image: lscr.io/linuxserver/speedtest-tracker:latest
      restart: unless-stopped
      container_name: speedtest-tracker
      ports:
          - 9006:80
      environment:
          - PUID=1000
          - PGID=1000
          - APP_KEY=${SPEEDTEST_APP_KEY}
          - ADMIN_PASSWORD=${SPEEDTEST_ADMIN_PASSWORD}
          - DB_CONNECTION=sqlite
          - MAIL_MAILER=smtp
          - MAIL_HOST=mailserver
          - MAIL_PORT=25
          - MAIL_USERNAME=null
          - MAIL_PASSWORD=null
          - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
          - MAIL_FROM_NAME="Speedtest Tracker"
          - MAIL_SCHEME=null
          - SPEEDTEST_SCHEDULE=6 */2 * * *
          - APP_TIMEZONE=Europe/Madrid
      volumes:
          - /docker/speedtest/data:/config
      networks:
        - homeassistant

networks:
  homeassistant:
    external: true
