version: '3.5'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
      #- '81:81'
    volumes:
      - /docker/nginx/data:/data
      - /docker/nginx/letsencrypt:/etc/letsencrypt
    networks:
        - homeassistant
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s

  cloudflare:
    image: erisamoe/cloudflared
    container_name: cloudflare
    command: tunnel run -token ${CLOUDFLARE_TOKEN}
    networks:
        - homeassistant
    restart: always

  vscode:
    image: linuxserver/code-server
    container_name: vscode
    volumes:
      - /docker/vscode/config:/config
      - /docker:/config/workspace
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: always
    networks:
        - homeassistant

  hisense_ac:
    image: deiger/aircon:0.3.14
    container_name: hisense_ac
    healthcheck:
      disable: true
    ports:
      - '8888:8888'
    environment:
      - CONFIG_DIR=/config
      - OPTIONS_FILE=/config/options.json
    volumes:
      - /docker/hisense_ac/config:/config
    networks:
        - homeassistant
        
networks:
  homeassistant:
      external: true