- platform: statistics
  name: bathroom_humidity_mean_over_last_24_hours
  entity_id: sensor.sensor_temp_aseo_humidity
  state_characteristic: mean
  unique_id: sensor.bathroom_humidity_mean_over_last_24_hours
  max_age:
    hours: 24
- platform: time_date
  display_options:
    - time
- platform: template
  sensors:
    minutes_next_sunrise:
      value_template: "{{((state_attr('sun.sun', 'next_rising')|as_timestamp|int - now()|as_timestamp|int)/60)|int}}"
    is_weekday:
      value_template: "{{ 'on' if 0 < now()|as_timestamp|timestamp_custom('%w')|int < 6 else 'off'  }}"
    extractor_uptime:
      value_template: >
        {% if is_state('switch.switch_extractor', 'on') %}
          {{ (as_timestamp(now()) - as_timestamp(states.switch.switch_extractor.last_changed)) | int }}
        {% else %}
          -1
        {% endif %}
    bathroom_current_to_average_humidity:
      friendly_name: "Bathroom Current to Average Humidity Difference"
      unique_id: 'sensor.bathroom_current_to_average_humidity'
      unit_of_measurement: "%"
      value_template: >-
        {% set avg_humidity = states('sensor.bathroom_humidity_mean_over_last_24_hours') | int %}
        {% set currrent_humidity = states('sensor.sensor_temp_aseo_humidity') | int %}
        {{ currrent_humidity - avg_humidity }}
    extractor_remaining:
      value_template: >
        {% if is_state('switch.switch_extractor', 'on') %}
          {% set base_stop_time = as_timestamp(states.switch.switch_extractor.last_changed) | float %}
          {% set bathroom_to_salon_humidity_diff = states('sensor.bathroom_to_salon_humidity') | float %}
          {% if bathroom_to_salon_humidity_diff > 4 %}
            {% set stop_time = base_stop_time + 1200 - as_timestamp(now()) %}  {# 20 minutes = 1200 seconds #}
          {% else %}
            {% set stop_time = base_stop_time + 300 - as_timestamp(now()) %}  {# 5 minutes = 300 seconds #}
          {% endif %}
          {{ stop_time }}
        {% else %}
          0
        {% endif %} 